apiVersion: v2
appVersion: 1.0.0
name: ociregistry
description: A pull-only, pull-through caching OCI image distribution server.
home: https://github.com/aceeric/ociregistry
type: application
keywords:
- oci
- distribution
- containerd
- mirror
- pull-through
- docker
sources:
- https://github.com/aceeric/ociregistry
version: 1.0.0
